package com.rabbit.examples;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class StringManipulationUtils {

	/**
	 * Root path segment for all publicly available REST resources
	 */
	public static final String EXTERNAL_URI_PREFIX = "mgmt";

	/**
	 * Shared (ADC and BIGIQ) worker path prefix. Required before the worker
	 * specific URI suffix
	 */
	public static final String SHARED_PATH_PREFIX = "shared/";

	/**
	 * Shared (ADC and BIGIQ) test worker path prefix. Required before the test
	 * worker specific URI suffix
	 */
	public static final String SHARED_TEST_PATH_PREFIX = SHARED_PATH_PREFIX + "test/";

	/**
	 * Centralized management (BIGIQ) worker path prefix. Required before the worker
	 * specific URI suffix
	 */
	public static final String CM_PATH_PREFIX = "cm/";

	/**
	 * Traffic management (BIGIP) worker path prefix. Required before the worker
	 * specific URI suffix
	 */
	public static final String TM_PATH_PREFIX = "tm/";

	public static void main(String[] args) {
		final String[] inputsArr = new String[] { "/mgmt/tm/sys/log-config/destination/splunk",
				"/mgmt/tm/ltm/html-rule/tag-raise-event", "/mgmt/tm/sys/service", "/mgmt/tm/sys/ucs", "/mgmt/tm/cli",
				"/mgmt/tm/sys/file/apache-ssl-cert", "/mgmt/tm/sys/dynad/key",
				"/mgmt/tm/ltm/message-routing/generic/router", "/mgmt/tm/ltm/profile/splitsessionserver",
				"/mgmt/tm/asm/owasp/policy-score", "/mgmt/tm/ltm/monitor/mysql", "/mgmt/tm/sys/dynad/settings",
				"/mgmt/tm/analytics/dns/generate-report", "/mgmt/tm/net/sfc/sf", "/mgmt/tm/sys/fpga/turboflex-profile",
				"/mgmt/tm/net/packet-filter", "/mgmt/tm/net/stp", "/mgmt/tm/live-update/threat-campaigns/installations",
				"/mgmt/tm/ltm/html-rule/comment-raise-event", "/mgmt/tm/net/rate-shaping/queue",
				"/mgmt/tm/sys/log-config/destination/management-port", "/mgmt/tm/net/stp-globals",
				"/mgmt/tm/live-update/browser-challenges/update-files", "/mgmt/tm/analytics/vcmp/generate-report",
				"/mgmt/tm/asm/file-transfer/uploads-private", "/mgmt/tm/util/gencert", "/mgmt/tm/util/ihealth",
				"/mgmt/shared/rpm-tasks", "/mgmt/tm/net/tunnels/vxlan", "/mgmt/tm/cm/failover-status",
				"/mgmt/tm/sys/file/ssl-key", "/mgmt/shared/root-framework-upgrades",
				"/mgmt/shared/server/messaging/settings/8100", "/mgmt/tm/net/routing/as-path",
				"/mgmt/tm/ltm/monitor/http", "/mgmt/tm/sys/icall/handler", "/mgmt/tm/sys/icall/script",
				"/mgmt/tm/ltm/auth/ldap", "/mgmt/tm/ltm/monitor/tcp-half-open", "/mgmt/tm/sys/nethsm",
				"/mgmt/shared/framework-info-tasks", "/mgmt/tm/sys/icall", "/mgmt/shared/authz/tokens",
				"/mgmt/shared/nodejs/loader-path-config", "/mgmt/tm/ltm/monitor/sip",
				"/mgmt/tm/ltm/message-routing/diameter", "/mgmt/shared/gossip", "/mgmt/net/software-status",
				"/mgmt/tm/sys/ntp", "/mgmt/tm/ltm/clientssl", "/mgmt/tm/net/tunnels/tunnel", "/mgmt/tm/sys/ha-status",
				"/mgmt/tm/ltm/monitor/sasp", "/mgmt/tm/ltm/default-node-monitor", "/mgmt/tm/net/route-domain",
				"/mgmt/shared/iapp/package-installer-tasks", "/mgmt/tm/sys/tmm-traffic",
				"/mgmt/tm/ltm/monitor/module-score", "/mgmt/tm/ltm/profile/diameter", "/mgmt/shared/echo",
				"/mgmt/shared/authz/roles", "/mgmt/tm/util/domain-tool", "/mgmt/tm/sys/restricted-module",
				"/mgmt/tm/ltm/cipher/rule", "/mgmt/tm/ltm/global-settings/general",
				"/mgmt/tm/net/routing/community-list", "/mgmt/tm/sys/snmp", "/mgmt/tm/sys/tmm-info",
				"/mgmt/tm/sys/daemon-log-settings/lind", "/mgmt/tm/analytics/swg-blocked/generate-report",
				"/mgmt/tm/sys/url-db/download-result", "/mgmt/tm/analytics/protocol-security/report-results",
				"/mgmt/tm/ltm/auth/ssl-ocsp", "/mgmt/tm/net", "/mgmt/tm/ltm/message-routing/sip/profile/session",
				"/mgmt/tm/ltm/tacdb/query", "/mgmt/cm/autodeploy/qkview-downloads", "/mgmt/tm/sys/software/image",
				"/mgmt/tm/ltm/persistence/hash", "/mgmt/tm/ltm/monitor/firepass", "/mgmt/tm/net/bwc",
				"/mgmt/tm/analytics/apm-api-protection/generate-report", "/mgmt/tm/sys/iprep",
				"/mgmt/tm/ltm/profile/sip", "/mgmt/tm/ltm/monitor/radius", "/mgmt/tm/ltm/profile/splitsessionclient",
				"/mgmt/tm/util/admdb", "/mgmt/tm/ltm/dns/cache/global-settings", "/mgmt/tm/net/tunnels/map",
				"/mgmt/tm/sys/log", "/mgmt/tm/live-update/asm-attack-signatures/availability", "/mgmt/toc",
				"/mgmt/shared/file-transfer/slot-transfer", "/mgmt/tm/ltm/dns/dnssec/zone",
				"/mgmt/tm/sys/icall/handler/triggered", "/mgmt/cm/autodeploy/software-volume-install",
				"/mgmt/tm/net/lldp-globals", "/mgmt/tm/ltm/tacdb/customdb", "/mgmt/tm/net/tunnels/lw4o6",
				"/mgmt/tm/sys/url-db", "/mgmt/tm/util/qkview", "/mgmt/tm/live-update/browser-challenges/availability",
				"/mgmt/sys/certificate-key-file-object", "/mgmt/tm/live-update/asm-attack-signatures/update-files",
				"/mgmt/tm/shared/licensing/activation", "/mgmt/tm/ltm/auth/profile", "/mgmt/shared/index/config",
				"/mgmt/tm/ltm/ifile", "/mgmt/tm/net/route", "/mgmt/tm/cm/device", "/mgmt/shared/iapp/template-loader",
				"/mgmt/tm/ltm/monitor/wmi", "/mgmt/device/common/trust/delete",
				"/mgmt/tm/ltm/message-routing/generic/pmbr-stats",
				"/mgmt/tm/live-update/server-technologies/install-schedule", "/mgmt/tm/ltm/monitor/external",
				"/mgmt/tm/ltm/profile/service", "/mgmt/tm/sys/application/apl-script",
				"/mgmt/tm/analytics/swg/report-results", "/mgmt/tm/sys/url-db/download-schedule", "/mgmt/tm/util/bash",
				"/mgmt/tm/sys/db", "/mgmt/tm/util/ipsecalgdb", "/mgmt/shared/rest/properties",
				"/mgmt/tm/shared/licensing/registration", "/mgmt/tm/sys/iprep-status",
				"/mgmt/tm/analytics/asm-policy-changes/report-results", "/mgmt/tm/sys/diags/ihealth-request",
				"/mgmt/net/platform", "/mgmt/tm/sys/log-config/destination/local-syslog",
				"/mgmt/tm/live-update/asm-attack-signatures", "/mgmt/tm/ltm/profile/http3",
				"/mgmt/tm/ltm/profile/http2", "/mgmt/tm/net/packet-filter-trusted", "/mgmt/tm/sys/crypto",
				"/mgmt/tm/analytics/dos-vis-attacks/generate-report", "/mgmt/tm/ltm/message-routing/sip/profile",
				"/mgmt/tm/sys/proc-info", "/mgmt/tm/sys/sflow/global-settings/system", "/mgmt/tm/sys/core",
				"/mgmt/tm/analytics/dos-vis-vips/report-results", "/mgmt/tm/cli/alias/private", "/mgmt/shared/skeleton",
				"/mgmt/tm/live-update/server-technologies", "/mgmt/tm/util/ping6", "/mgmt/tm/ltm/dns/tsig-key",
				"/mgmt/tm/net/ike-evt-stat", "/mgmt/tm/sys/hypervisor-info", "/mgmt/shared/restricted-store/settings",
				"/mgmt/tm/sys/turboflex/profile/all", "/mgmt/tm/ltm/profile/ipsecalg",
				"/mgmt/tm/live-update/server-technologies/installations",
				"/mgmt/tm/analytics/ssl-orchestrator/report-results", "/mgmt/shared/iapp/package-management-tasks",
				"/mgmt/tm/live-update/file-transfer/downloads", "/mgmt/tm/net/ipsec/ike-daemon",
				"/mgmt/tm/cloud/services/iapp", "/mgmt/tm/net/tunnels/geneve", "/mgmt/tm/util/traceroute6",
				"/mgmt/tm/sys/crypto/key", "/mgmt/tm/util/diadb", "/mgmt/tm/apiprotection/api-protection-profile",
				"/mgmt/tm/util/telnet", "/mgmt/tm/sys/log-config/destination", "/mgmt/tm/asm",
				"/mgmt/shared/iapp/package-replication-tasks", "/mgmt/tm/analytics/cpu/report-results",
				"/mgmt/tm/analytics/realtime-session/http", "/mgmt/tm/ltm/profile/pptp",
				"/mgmt/tm/sys/nethsm/async-queue-stat", "/mgmt/tm/net/cos/map-dscp", "/mgmt/tm/net/routing/prefix-list",
				"/mgmt/tm/sys/daemon-log-settings/clusterd", "/mgmt/tm/sys/crypto/encrypted-attributes",
				"/mgmt/shared/settings/api-status/availability", "/mgmt/tm/analytics/realtime-session/dos-l3",
				"/mgmt/tm/analytics/network/generate-report", "/mgmt/shared/iapp/affinity/local",
				"/mgmt/tm/live-update/file-transfer/uploads-private", "/mgmt/tm/sys/crypto/ca-bundle-manager",
				"/mgmt/tm/ltm/monitor/dns", "/mgmt/tm/cli/version", "/mgmt/tm/ltm/html-rule",
				"/mgmt/tm/sys/icall/publisher", "/mgmt/tm/net/bwc/priority-group",
				"/mgmt/cm/autodeploy/software-image-downloads", "/mgmt/tm/sys/nethsm/pkcs11d-stat",
				"/mgmt/tm/analytics/dos-vis-vips/generate-report", "/mgmt/shared/server/8100",
				"/mgmt/shared/iapp/build-package", "/mgmt/tm/ltm/profile/server-ssl", "/mgmt/shared/diagnostics",
				"/mgmt/tm/net/interface", "/mgmt/tm/net/tunnels/v6rd", "/mgmt/tm/util/fips-util",
				"/mgmt/shared/authn/providers/local/groups", "/mgmt/tm/ltm/message-routing/mqtt/pmbr-stats",
				"/mgmt/tm/cm/device-group", "/mgmt/tm/sys/management-dhcp", "/mgmt/cm/autodeploy/mgmt-mac",
				"/mgmt/tm/sys/mcp-state", "/mgmt/tm/analytics/realtime/host-ram", "/mgmt/tm/ltm/dns/cache/transparent",
				"/mgmt/tm/ltm/snat-translation", "/mgmt/tm/analytics/asm-learning-suggestions/generate-report",
				"/mgmt/tm/ltm/message-routing/sip/pmbr-stats/router", "/mgmt/tm/sys/crypto/pkcs12",
				"/mgmt/tm/sys/internal-proxy", "/mgmt/tm/live-update",
				"/mgmt/tm/ltm/message-routing/diameter/pmbr-stats", "/mgmt/tm/net/service-policy",
				"/mgmt/tm/ltm/profile/one-connect", "/mgmt/tm/analytics/proc-cpu/generate-report",
				"/mgmt/tm/ltm/profile/udp", "/mgmt/tm/sys/crypto/fips/key", "/mgmt/tm/sys/file/dashboard-viewset",
				"/mgmt/tm/util/dnat", "/mgmt/tm/access/session/session-variables", "/mgmt/tm/sys/ecm/config",
				"/mgmt/tm/sys/ecm/register", "/mgmt/tm/ltm/profile/request-adapt",
				"/mgmt/cm/system/authn/providers/tmos", "/mgmt/tm/ltm/profile/fix",
				"/mgmt/tm/access/generate/api-protection-profile", "/mgmt/tm/ltm/dns/analytics/global-settings",
				"/mgmt/shared/file-transfer/ucs-downloads", "/mgmt/tm/shared/sys/backup", "/mgmt/tm/sys/log-config",
				"/mgmt/tm/ltm/profile/rtsp", "/mgmt/tm/sys/turboflex/profile/feature",
				"/mgmt/tm/ltm/persistence/dest-addr", "/mgmt/shared/resolver/groups",
				"/mgmt/tm/analytics/swg/generate-report", "/mgmt/tm/ltm/traffic-class", "/mgmt/tm/ltm/profile/wa-cache",
				"/mgmt/tm/ltm/monitor/ftp", "/mgmt/tm/analytics/cpu/generate-report", "/mgmt/tm/ltm/dns/dnssec",
				"/mgmt/tm/adc/fileobject/ssl-csr",
				"/mgmt/shared/authn/providers/remote/2c18e486-683a-3db1-a645-ad8523223b72/users",
				"/mgmt/tm/cm/sniff-updates", "/mgmt/tm/ltm/global-settings", "/mgmt/tm/adc/fileobject/ssl-crl",
				"/mgmt/tm/ltm/snatpool", "/mgmt/tm/sys/nethsm/sync-queue-stat", "/mgmt/tm/net/ipsec",
				"/mgmt/tm/net/packet-tester", "/mgmt/subscriptions", "/mgmt/tm/ltm/monitor/smb",
				"/mgmt/tm/analytics/realtime-session/dos-vis-attacks", "/mgmt/tm/net/wccp",
				"/mgmt/tm/sys/sflow/global-settings", "/mgmt/tm/cm/key", "/mgmt/tm/sys/aom",
				"/mgmt/tm/sys/log-config/filter", "/mgmt/tm/live-update/server-technologies/update-files",
				"/mgmt/tm/sys/folder", "/mgmt/shared/diagnostics/heap-dump",
				"/mgmt/tm/ltm/message-routing/mqtt/pmbr-stats/session", "/mgmt/tm/net/fdb/vlan",
				"/mgmt/tm/live-update/credential-stuffing", "/mgmt/shared/iapp/block-refresh-stats",
				"/mgmt/tm/ltm/tacdb/customdb-file", "/mgmt/tm/ltm/html-rule/tag-remove",
				"/mgmt/tm/analytics/tcp-analytics/report-results",
				"/mgmt/tm/analytics/protocol-inspection/report-results", "/mgmt/tm/sys/fix-connection",
				"/mgmt/tm/sys/daemon-log-settings/icr-eventd", "/mgmt/tm/ltm/rule", "/mgmt/tm/sys/ipfix/irules",
				"/mgmt/shared/iapp/installed-packages", "/mgmt/tm/access/redeploy-iapp-tasks",
				"/mgmt/tm/ltm/html-rule/tag-prepend-html", "/mgmt/tm/net/tunnels/wccp", "/mgmt/tm/access/file-download",
				"/mgmt/tm/net/routing/all", "/mgmt/net/hardware-version-info", "/mgmt/tm/sys/ecm/cloud-provider",
				"/mgmt/tm/sys/sflow/data-source/http", "/mgmt/tm/live-update/behavioral-waf/install-schedule",
				"/mgmt/tm/sys/global-settings", "/mgmt/tm/sys/software/block-device-hotfix",
				"/mgmt/tm/sys/file/browser-capabilities-db", "/mgmt/shared/package-deployments",
				"/mgmt/tm/analytics/vcmp/report-results", "/mgmt/tm/util/vconsole",
				"/mgmt/tm/analytics/udp/generate-report", "/mgmt/tm/sys/icmp-stat",
				"/mgmt/tm/net/ipsec/manual-security-association", "/mgmt/tm/cloud/ltm/pool-members",
				"/mgmt/shared/certificate-whitelist-tasks", "/mgmt/tm/sys/log-rotate",
				"/mgmt/shared/file-transfer/security/ips-signatures", "/mgmt/tm/ltm/profile/html",
				"/mgmt/tm/util/zebos", "/mgmt/tm/ltm/monitor/wap", "/mgmt/tm/net/port-mirror",
				"/mgmt/tm/ltm/dns/nameserver", "/mgmt/tm/analytics/bot-defense-event/report-results",
				"/mgmt/tm/net/router-advertisement", "/mgmt/tm/util", "/mgmt/tm/sys/icall/handler/periodic",
				"/mgmt/cm/autodeploy/default-boot-volume", "/mgmt/tm/auth/source", "/mgmt/sys/tmm-stat",
				"/mgmt/tm/ltm/clientssl/ocsp-stapling-responses", "/mgmt/tm/cm/cert", "/mgmt/tm/sys/geoip",
				"/mgmt/shared/authn/providers/remote", "/mgmt/tm/ltm/cipher/group", "/mgmt/tm/ltm/monitor/mqtt",
				"/mgmt/tm/analytics/http/generate-report", "/mgmt/tm/net/sfc",
				"/mgmt/tm/analytics/protocol-security-http/report-results", "/mgmt/sys/all-certificate-file-object",
				"/mgmt/tm/ltm/dns/dnssec/key", "/mgmt/shared/analytics/avr-proxy-tasks",
				"/mgmt/tm/sys/crypto/fips/nethsm-partition", "/mgmt/tm/auth/tacacs", "/mgmt/tm/sys/file/ssl-cert",
				"/mgmt/tm/analytics/generic/report-results", "/mgmt/tm/analytics/pem/report-results",
				"/mgmt/tm/sys/icall/handler/perpetual", "/mgmt/shared/authz/remote-resources",
				"/mgmt/tm/analytics/memory/report-results", "/mgmt/shared/device-certificates",
				"/mgmt/tm/live-update/behavioral-waf", "/mgmt/shared/restricted-store/storage",
				"/mgmt/shared/differencer", "/mgmt/tm/sys/integrity", "/mgmt/tm/util/fips-card-sync",
				"/mgmt/tm/util/racoonctl", "/mgmt/tm/access/file-info",
				"/mgmt/tm/analytics/system-monitor/generate-report", "/mgmt/tm/shared/sys/config-restore",
				"/mgmt/tm/sys/pfman/device", "/mgmt/tm/live-update/browser-challenges/installations",
				"/mgmt/shared/file-transfer/bulk", "/mgmt/tm/sys/sflow/receiver",
				"/mgmt/tm/analytics/disk-info/report-results", "/mgmt/tm/analytics/protocol-security/generate-report",
				"/mgmt/tm/live-update/behavioral-waf/availability", "/mgmt/tm/ltm/monitor/tcp-echo",
				"/mgmt/shared/tmsh-parser", "/mgmt/tm/sys/file/external-monitor", "/mgmt/shared/authn/providers",
				"/mgmt/tm/sys/dns", "/mgmt/tm/net/rst-cause", "/mgmt/tm/sys/config-diff", "/mgmt/tm/util/ssh-keyswap",
				"/mgmt/tm/auth/remote-role", "/mgmt/tm/sys/performance/system", "/mgmt/tm/ltm/monitor/inband",
				"/mgmt/tm/sys/fpga", "/mgmt/tm/ltm/data-group/external", "/mgmt/shared/managed-device-group-tasks",
				"/mgmt/tm/ltm/auth/ocsp-responder", "/mgmt/tm/sys/ip-stat", "/mgmt/tm/file/apm/resource/sandbox-file",
				"/mgmt/tm/analytics/application-security-anomalies/generate-report",
				"/mgmt/shared/identified-devices/config/device-trust-certs", "/mgmt/tm/ltm/message-routing/mqtt/route",
				"/mgmt/tm/cm/traffic-group", "/mgmt/tm/sys/integrity/status-check", "/mgmt/tm/services",
				"/mgmt/shared/device-partition-owners", "/mgmt/tm/sys/sflow/global-settings/http",
				"/mgmt/tm/ltm/profile/ramcache", "/mgmt/tm/ltm/monitor/soap",
				"/mgmt/sys/apache-certificate-file-object", "/mgmt/tm/ltm/dns",
				"/mgmt/tm/ltm/message-routing/mqtt/pmbr-stats/router", "/mgmt/tm/sys/crypto/cert-validator/crl",
				"/mgmt/tm/sys/management-ovsdb", "/mgmt/tm/ltm/eviction-policy", "/mgmt/tm/sys/daemon-ha",
				"/mgmt/tm/sys/crypto/master-key", "/mgmt/tm/sys/crypto/crl", "/mgmt/tm/net/bwc/policy",
				"/mgmt/tm/sys/turboflex/warning", "/mgmt/shared/nsyncd", "/mgmt/tm/ltm/monitor/ldap",
				"/mgmt/tm/sys/application", "/mgmt/tm/ltm/auth/radius-server", "/mgmt/tm/util/verify-encryption",
				"/mgmt/tm/sys/clock", "/mgmt/tm/transaction", "/mgmt/shared/identified-devices/config/device-refresh",
				"/mgmt/tm/net/tunnels/endpoint", "/mgmt/shared/authz/users", "/mgmt/tm/net/routing/profile/bgp",
				"/mgmt/tm/access/profile-access-misc-stats", "/mgmt/sys/cpu-info-stat",
				"/mgmt/tm/net/ipsec/ipsec-policy", "/mgmt/tm/sys/crypto/csr", "/mgmt/tm/live-update/bot-signatures",
				"/mgmt/shared/cache", "/mgmt/tm/security/cloud-services", "/mgmt/shared/file-transfer/ecm",
				"/mgmt/tm/sys/dynad/instrumentation", "/mgmt/tm/live-update/behavioral-waf/installations",
				"/mgmt/tm/net/self", "/mgmt/tm/file/apm/aaa/kerberos-keytab-file",
				"/mgmt/tm/ltm/message-routing/sip/transport-config", "/mgmt/tm/sys/pfman/consumer",
				"/mgmt/tm/sys/performance/throughput", "/mgmt/tm/analytics/pem/generate-report",
				"/mgmt/tm/sys/application/service", "/mgmt/tm/sys/crypto/allow-key-export",
				"/mgmt/tm/util/platform_check", "/mgmt/tm/analytics/dns-rpz/generate-report",
				"/mgmt/tm/sys/log-config/destination/arcsight", "/mgmt/tm/net/tunnels/gre",
				"/mgmt/tm/util/bigip_appliance_add", "/mgmt/tm/sys/icontrol-soap",
				"/mgmt/tm/analytics/asm-policy-changes/generate-report",
				"/mgmt/tm/file/apm/policy/customization-template-file", "/mgmt/tm/analytics/realtime/throughput",
				"/mgmt/tm/sys/connection", "/mgmt/tm/security/cloud-services/endpoint",
				"/mgmt/tm/sys/application/template-model-tasks", "/mgmt/tm/sys/disk",
				"/mgmt/tm/sys/diags/ihealth-result", "/mgmt/tm/ltm/policy-strategy",
				"/mgmt/tm/analytics/application-security-network/report-results",
				"/mgmt/tm/analytics/udp/report-results", "/mgmt/tm/sys/log-config/publisher",
				"/mgmt/tm/ltm/message-routing/diameter/pmbr-stats/session", "/mgmt/tm/sys/crypto/fips",
				"/mgmt/tm/cm/watch-sys-device", "/mgmt/tm/ltm/node", "/mgmt/tm/access/bundle-install-tasks",
				"/mgmt/tm/ltm/message-routing/mqtt/peer", "/mgmt/net/tunnel", "/mgmt/tm/net/routing/access-list",
				"/mgmt/shared/monitor-invalid-owners", "/mgmt/tm/sys/file",
				"/mgmt/tm/sys/log-config/destination/remote-syslog", "/mgmt/tm/util/sipdb", "/mgmt/tm/sys/telemd",
				"/mgmt/tm/util/lsndb", "/mgmt/tm/ltm/urlcat-cloud-cache", "/mgmt/tm/sys/pfman",
				"/mgmt/net/software-desired", "/mgmt/tm/analytics/traffic-classification/generate-report",
				"/mgmt/tm/analytics/disk-info/generate-report", "/mgmt/tm/auth/radius", "/mgmt/tm/auth/login-failures",
				"/mgmt/tm/net/f5optics", "/mgmt/tm/sys/performance/dnssec", "/mgmt/tm/ltm/profile/websocket",
				"/mgmt/tm/net/cos/map-8021p", "/mgmt/tm/net/ipsec-stat",
				"/mgmt/tm/ltm/message-routing/generic/transport-config", "/mgmt/tm/ltm/virtual",
				"/mgmt/shared/tm/local-icontrol-soap-proxy", "/mgmt/tm/ltm/cipher",
				"/mgmt/tm/ltm/message-routing/diameter/peer", "/mgmt/tm/net/fdb",
				"/mgmt/tm/ltm/message-routing/generic/route",
				"/mgmt/tm/ltm/message-routing/generic/pmbr-stats/protocol", "/mgmt/tm/ltm/monitor/nntp",
				"/mgmt/tm/net/ipsec/traffic-selector", "/mgmt/shared/device-certificate",
				"/mgmt/tm/cloud/ltm/node-addresses", "/mgmt/shared/featureSettings", "/mgmt/tm/net/interface-ddm",
				"/mgmt/tm/net/address-list", "/mgmt/tm/sys/file/system-ssl-key", "/mgmt/access/file-path-manager",
				"/mgmt/tm/ltm/monitor/udp", "/mgmt/tm/sys/url-db/url-category",
				"/mgmt/tm/ltm/html-rule/tag-append-html", "/mgmt/tm/ltm/profile/client-ldap",
				"/mgmt/tm/sys/icall/istats-trigger", "/mgmt/tm/net/dag-globals", "/mgmt/tm/net/sfc/hop",
				"/mgmt/tm/sys/crypto/cert-validator/ocsp", "/mgmt/tm/sys/management-route",
				"/mgmt/tm/ltm/message-routing", "/mgmt/tm/ltm/message-routing/sip/route",
				"/mgmt/tm/analytics/traffic-classification/report-results",
				"/mgmt/tm/live-update/bot-signatures/installations", "/mgmt/tm/analytics/realtime/tmm-ram",
				"/mgmt/tm/cm/remove-from-trust", "/mgmt/tm/auth/cert-ldap", "/mgmt/tm/ltm/message-routing/mqtt",
				"/mgmt/shared/authz/resource-groups", "/mgmt/tm/ltm/message-routing/diameter/pmbr-stats/router",
				"/mgmt/tm/analytics/http/report-results",
				"/mgmt/shared/resolver/device-groups/tm-shared-all-big-ips/devices", "/mgmt/tm/ltm/profile/dhcpv6",
				"/mgmt/shared/group-task", "/mgmt/tm/ltm/profile/dhcpv4", "/mgmt/tm/net/routing/extcommunity-list",
				"/mgmt/tm/live-update/threat-campaigns", "/mgmt/tm/sys/software/status", "/mgmt/tm/sys/cluster",
				"/mgmt/tm/ltm/message-routing/generic", "/mgmt/tm/sys/daemon-log-settings/tmm",
				"/mgmt/shared/file-transfer/bulk/uploads", "/mgmt/tm/util/sys-icheck",
				"/mgmt/shared/iapp/directory-management-recursive", "/mgmt/tm/ltm/auth", "/mgmt/tm/sys/ha-group",
				"/mgmt/tm/access/profile-rewrite/stats", "/mgmt/tm/sys/diags/ihealth", "/mgmt/shared/iapp/blocks",
				"/mgmt/tm/sys/performance/all-stats", "/mgmt/tm/util/sftp", "/mgmt/tm/util/test-monitor",
				"/mgmt/tm/access/read-user-group", "/mgmt/tm/cloud/ltm/pools",
				"/mgmt/tm/analytics/bot-defense-event/generate-report", "/mgmt/tm/ltm/dns/cache/resolver",
				"/mgmt/tm/util/updatecheck", "/mgmt/shared/diagnostics/runtime",
				"/mgmt/cm/autodeploy/cluster-software-images", "/mgmt/net/software-hotfix",
				"/mgmt/tm/analytics/ip-layer/generate-report",
				"/mgmt/shared/file-transfer/traffic-classification/application-signatures",
				"/mgmt/tm/analytics/dns/report-results", "/mgmt/tm/sys/license", "/mgmt/shared/manager-access-check",
				"/mgmt/tm/ltm/persistence/msrdp", "/mgmt/shared/iapp/rpm-spec-creator", "/mgmt/shared/authn/login",
				"/mgmt/tm/sys/autoscale-group", "/mgmt/tm/sys/ipfix/element",
				"/mgmt/tm/ltm/message-routing/generic/peer", "/mgmt/shared/iapp/package-downloads",
				"/mgmt/tm/cli/alias", "/mgmt/tm/net/ipsec/ipsec-sa", "/mgmt/shared/chassis-framework-upgrades",
				"/mgmt/tm/analytics/asm-bypass/generate-report", "/mgmt/tm/access/certkey-file-helper",
				"/mgmt/tm/live-update/credential-stuffing/install-schedule", "/mgmt/tm/util/serverssl-ciphers",
				"/mgmt/tm/ltm/nat-stats", "/mgmt/net/route", "/mgmt/tm/sys/software/signature",
				"/mgmt/shared/analytics/event-aggregation-tasks", "/mgmt/tm/sys/sync-sys-files",
				"/mgmt/tm/ltm/monitor/snmp-dca", "/mgmt/tm/analytics/asm-memory/report-results",
				"/mgmt/shared/authz/tmos-default-roles", "/mgmt/tm/sys/console",
				"/mgmt/tm/ltm/message-routing/diameter/profile/router", "/mgmt/tm/ltm/profile/certificate-authority",
				"/mgmt/tm/sys/software/update", "/mgmt/tm/live-update/file-transfer/uploads",
				"/mgmt/tm/net/lldp-neighbors", "/mgmt/tm/analytics/cpu-per-vip/generate-report",
				"/mgmt/tm/sys/raid/bay", "/mgmt/tm/ltm/profile/http-proxy-connect",
				"/mgmt/tm/analytics/proc-cpu/report-results", "/mgmt/tm/sys/config",
				"/mgmt/tm/ltm/dns/cache/records/key", "/mgmt/tm/security/cloud-services/application",
				"/mgmt/tm/live-update/browser-challenges", "/mgmt/tm/file/apm/aaa/ping-access-properties-files",
				"/mgmt/shared/publisher", "/mgmt/tm/analytics/tcp/generate-report", "/mgmt/tm/net/vlan-group",
				"/mgmt/tm/util/tracepath6", "/mgmt/shared/iapp/finder-tasks",
				"/mgmt/tm/ltm/message-routing/sip/profile/router", "/mgmt/tm/sys/diags", "/mgmt/tm/sys/crypto/client",
				"/mgmt/tm/ltm/message-routing/sip", "/mgmt/tm/ltm/message-routing/mqtt/profile/session",
				"/mgmt/tm/cli/script", "/mgmt/tm/auth/ldap", "/mgmt/tm/asm/owasp/policy-setting",
				"/mgmt/tm/sys/dynad/status", "/mgmt/tm/net/arp", "/mgmt/tm/analytics/realtime-session/dos-vis-vips",
				"/mgmt/tm/ltm/message-routing/generic/protocol", "/mgmt/tm/apiprotection/openapi-parser",
				"/mgmt/tm/sys/ltcfg-class", "/mgmt/tm/sys/log-config/destination/remote-high-speed-log",
				"/mgmt/tm/auth/user", "/mgmt/tm/wom/profile/isession", "/mgmt/tm/ltm/auth/crldp-server",
				"/mgmt/shared/tmsh-resource", "/mgmt/tm/analytics/memory-per-process/generate-report",
				"/mgmt/tm/ltm/global-settings/traffic-control", "/mgmt/tm/adc/fileobject/ssl-key", "/mgmt/tm/sys/ecm",
				"/mgmt/tm/ltm/html-rule/tag-remove-attribute", "/mgmt/tm/ltm/monitor/gateway-icmp", "/mgmt/tm/net/vlan",
				"/mgmt/tm/analytics/dos-vis-attacks/report-results", "/mgmt/shared/save-config",
				"/mgmt/tm/ltm/data-group", "/mgmt/tm/ltm/monitor/icmp", "/mgmt/tm/analytics/sip/report-results",
				"/mgmt/tm/ltm/persistence/global-settings", "/mgmt/shared/diagnostics/api-usage",
				"/mgmt/tm/ltm/profile/client-ssl", "/mgmt/shared/certificates/retrieve-remote-host-certificate",
				"/mgmt/shared/authn/root", "/mgmt/tm/live-update/asm-attack-signatures/install-schedule",
				"/mgmt/shared/iapp/stage-package-install", "/mgmt/tm/ltm/profile/sctp", "/mgmt/tm/sys/pva-traffic",
				"/mgmt/tm/cm", "/mgmt/tm/ltm/global-settings/connection", "/mgmt/tm/net/sfc/chain",
				"/mgmt/shared/echo-js", "/mgmt/tm/net/cmetrics", "/mgmt/tm/sys/log-config/destination/alertd",
				"/mgmt/tm/util/platform_diag", "/mgmt/tm/sys/crypto/server", "/mgmt/tm/asm/file-transfer/downloads",
				"/mgmt/net/admin-ip", "/mgmt/tm/ltm/persistence/universal",
				"/mgmt/shared/identified-devices/config/discovery", "/mgmt/shared/snapshot",
				"/mgmt/tm/auth/password-policy", "/mgmt/tm/sys/feature-module",
				"/mgmt/tm/asm/file-transfer/downloads-private", "/mgmt/tm/shared/bigip-failover-state",
				"/mgmt/tm/util/qkcloud", "/mgmt/tm/analytics/application-security/generate-report",
				"/mgmt/tm/file/apm/policy/customization-group", "/mgmt/tm/ltm/monitor/snmp-dca-base",
				"/mgmt/tm/cli/global-settings", "/mgmt/tm/ltm/auth/ssl-crldp", "/mgmt/tm/ltm/dns/analytics",
				"/mgmt/tm/ltm/profile/gtp", "/mgmt/tm/analytics/asm-enforced-entities/report-results",
				"/mgmt/tm/analytics/realtime/cpu", "/mgmt/tm/cm/watch-trafficgroup-device",
				"/mgmt/tm/analytics/dos-l3/generate-report", "/mgmt/tm/analytics/cpu-per-vip/report-results",
				"/mgmt/shared/iapp/export-tasks", "/mgmt/tm/ltm/clientssl-proxy", "/mgmt/tm/ltm/profile/tftp",
				"/mgmt/tm/ltm/profile/web-acceleration", "/mgmt/tm/net/packet-tester/security", "/mgmt/net/vlan-group",
				"/mgmt/shared/iapp/package-remover-tasks", "/mgmt/tm/analytics/memory/generate-report",
				"/mgmt/net/sys-device", "/mgmt/tm/net/dns-resolver", "/mgmt/tm/sys/file/lwtunneltbl",
				"/mgmt/shared/framework-upgrades", "/mgmt/tm/analytics/memory-per-process/report-results",
				"/mgmt/tm/security/cloud-services/endpoint-stats", "/mgmt/tm/sys/crypto/check-cert",
				"/mgmt/cm/autodeploy/software-image-uploads", "/mgmt/tm/analytics/asm-bypass/report-results",
				"/mgmt/shared/device-discovery-tasks/event/types", "/mgmt/tm/ltm/dns/cache/records/rrset",
				"/mgmt/tm/ltm/profile/dns-logging", "/mgmt/tm/ltm/dns/cache/records/msg",
				"/mgmt/tm/access/oidc/discover", "/mgmt/tm/sys/application/template-model", "/mgmt/tm/cli/preference",
				"/mgmt/tm/live-update/browser-challenges/install-schedule", "/mgmt/tm/net/tunnels/tcp-forward",
				"/mgmt/tm/net/routing/bfd", "/mgmt/shared/iapp/processors/noop", "/mgmt/tm/access/customization/xml",
				"/mgmt/shared/iapp/update-named-conf", "/mgmt/tm/net/rate-shaping/drop-policy", "/mgmt/shared/api",
				"/mgmt/tm/analytics/system-monitor/report-results", "/mgmt/tm/net/tunnels/fec-stat",
				"/mgmt/tm/sys/air-filter-reset", "/mgmt/tm/ltm/dns/cache", "/mgmt/tm/ltm/message-routing/sip/peer",
				"/mgmt/tm/net/routing/bgp", "/mgmt/tm/ltm/profile/imap", "/mgmt/tm/ltm/traffic-matching-criteria",
				"/mgmt/shared/device-partition-owners-cluster", "/mgmt/tm/analytics/realtime-session/dos-vis-common",
				"/mgmt/tm/ltm/pool", "/mgmt/tm", "/mgmt/tm/util/traceroute", "/mgmt/tm/net/port-list",
				"/mgmt/tm/util/tracepath", "/mgmt/tm/sys/raid", "/mgmt/device/big-ip/sys/license/update",
				"/mgmt/tm/ltm/profile/socks", "/mgmt/tm/util/get-ccn-dossier", "/mgmt/shared/file-transfer/ucs-uploads",
				"/mgmt/shared/nodejs/process/memory", "/mgmt/tm/cloud/cm/device-group",
				"/mgmt/tm/ltm/monitor/virtual-location", "/mgmt/tm/analytics/swg-blocked/report-results", "/mgmt/odata",
				"/mgmt/tm/ltm/profile/statistics", "/mgmt/tm/net/ndp", "/mgmt/tm/net/cos", "/mgmt/tm/util/dig",
				"/mgmt/shared/file-transfer/security/ips-updates", "/mgmt/shared/iapp/affinity/all",
				"/mgmt/tm/analytics/ssl-orchestrator-service-virtual/generate-report",
				"/mgmt/tm/sys/crypto/fips/external-hsm", "/mgmt/shared/tmsh-shell", "/mgmt/tm/ltm/persistence/cookie",
				"/mgmt/tm/sys/daemon-log-settings/csyncd", "/mgmt/tm/live-update/bot-signatures/update-files",
				"/mgmt/tm/cli/transaction", "/mgmt/tm/sys/management-proxy-config", "/mgmt/tm/ltm/persistence",
				"/mgmt/tm/analytics/dns-rpz/report-results", "/mgmt/shared/diagnostics/logs", "/mgmt/tm/ltm/dns/zone",
				"/mgmt/tm/ltm/monitor/rpc", "/mgmt/tm/util/unix-mv", "/mgmt/tm/cm/trust-domain",
				"/mgmt/shared/snapshot-task", "/mgmt/tm/ltm/virtual-address", "/mgmt/tm/sys/sshd",
				"/mgmt/tm/net/routing/profile", "/mgmt/tm/analytics/network/report-results",
				"/mgmt/tm/ltm/tacdb/licenseddb-file", "/mgmt/tm/cm/watch-devicegroup-device", "/mgmt/tm/sys/ready",
				"/mgmt/shared/resolver/device-groups", "/mgmt/tm/sys/file/device-capabilities-db",
				"/mgmt/tm/util/unix-ls", "/mgmt/tm/ltm/profile/http", "/mgmt/tm/net/routing",
				"/mgmt/tm/file/apm/epsec/epsec-file-object", "/mgmt/tm/ltm/monitor/smtp", "/mgmt/tm/sys/software",
				"/mgmt/tm/analytics/application-security-anomalies/report-results", "/mgmt/tm/cm/sync-status",
				"/mgmt/tm/live-update/threat-campaigns/availability", "/mgmt/tm/net/trunk",
				"/mgmt/tm/ltm/auth/ssl-cc-ldap", "/mgmt/tm/ltm/profile/smtps", "/mgmt/tm/ltm/monitor/oracle",
				"/mgmt/tm/ltm/profile/tcp", "/mgmt/tm/ltm/urlcat-query",
				"/mgmt/tm/analytics/ssl-orchestrator-service-virtual/report-results", "/mgmt/tm/sys/file/ssl-csr",
				"/mgmt/tm/analytics/application-security/report-results", "/mgmt/tm/ltm/rule-profiler",
				"/mgmt/tm/wom/profile", "/mgmt/tm/security/cloud-services/application-stats", "/mgmt/tm/util/scp",
				"/mgmt/tm/util/unix-rm", "/mgmt/tm/sys/ipfix/destination", "/mgmt/net/self", "/mgmt/tm/sys",
				"/mgmt/tm/net/tunnels/ppp", "/mgmt/tm/sys/performance/dnsexpress", "/mgmt/tm/ltm/profile/radius",
				"/mgmt/shared/identified-devices/config/device-info", "/mgmt/tm/sys/file/ssl-crl",
				"/mgmt/tm/net/vlan-allowed", "/mgmt/tm/sys/dynad/rpm", "/mgmt/tm/util/imish",
				"/mgmt/tm/net/ipsec/ike-peer", "/mgmt/tm/net/interface-cos", "/mgmt/tm/ltm/html-rule/comment-remove",
				"/mgmt/tm/util/netstat", "/mgmt/tm/sys/crypto/cert-order-manager", "/mgmt/tm/sys/smtp-server",
				"/mgmt/tm/ltm/monitor/mssql", "/mgmt/tm/sys/crypto/cert-validator", "/mgmt/tm/gtm/sync-status",
				"/mgmt/tm/net/rate-shaping", "/mgmt/tm/ltm/profile/xml", "/mgmt/tm/analytics/fw-nat/generate-report",
				"/mgmt/tm/net/clone-stats", "/mgmt/tm/sys/daemon-log-settings/icrd",
				"/mgmt/tm/ltm/message-routing/generic/pmbr-stats/router", "/mgmt/tm/ltm/tacdb/licenseddb",
				"/mgmt/shared/user-role", "/mgmt/tm/net/timer-policy", "/mgmt/tm/sys/state-mirroring",
				"/mgmt/tm/sys/turboflex/features", "/mgmt/tm/analytics/realtime/adm", "/mgmt/tm/net/tunnels",
				"/mgmt/shared/file-transfer/uploads",
				"/mgmt/tm/analytics/application-security-incidents/report-results", "/mgmt/tm/net/ike-msg-stat",
				"/mgmt/tm/security/firewall/management-ip-rules", "/mgmt/tm/ltm/message-routing/diameter/route",
				"/mgmt/tm/file/apm/policy/customization-image-file", "/mgmt/tm/ltm/auth/kerberos-delegation",
				"/mgmt/tm/net/self-allow", "/mgmt/tm/security", "/mgmt/tm/sys/provision", "/mgmt/tm/sys/host-info",
				"/mgmt/shared/device-discovery-tasks", "/mgmt/tm/adc/fileobject/ssl-cert", "/mgmt/tm/ltm/profile/pop3",
				"/mgmt/shared", "/mgmt/tm/sys/memory", "/mgmt/tm/sys/sflow/global-settings/vlan",
				"/mgmt/tm/live-update/file-transfer/downloads-private", "/mgmt/tm/net/rate-shaping/shaping-policy",
				"/mgmt/tm/ltm/global-settings/rule", "/mgmt/tm/ltm/snat", "/mgmt/tm/analytics/asm-cpu/generate-report",
				"/mgmt/tm/sys/fpga/info", "/mgmt/tm/analytics/application-security-incidents/generate-report",
				"/mgmt/tm/ltm/message-routing/sip/pmbr-stats/session", "/mgmt/shared/iapp/icr-configuration",
				"/mgmt/tm/live-update/credential-stuffing/update-files", "/mgmt/tm/sys/cpu", "/mgmt/tm/sys/syslog",
				"/mgmt/tm/sys/log-config/destination/ipfix", "/mgmt/tm/analytics/tcp/report-results",
				"/mgmt/shared/iapp/global-installed-packages", "/mgmt/cm/autodeploy/mgmt-dhcp",
				"/mgmt/tm/sys/software/update-status", "/mgmt/shared/authz/effective-permissions",
				"/mgmt/tm/sys/application/custom-stat", "/mgmt/tm/sys/performance/connections",
				"/mgmt/tm/sys/turboflex", "/mgmt/tm/sys/software/hotfix", "/mgmt/tm/ltm/policy",
				"/mgmt/tm/net/bwc/probe", "/mgmt/shared/bulk/install",
				"/mgmt/tm/analytics/realtime-session/system-monitor",
				"/mgmt/tm/ltm/message-routing/diameter/transport-config", "/mgmt/tm/ltm/persistence/sip",
				"/mgmt/shared/device-availability", "/mgmt/tm/analytics/afm-sweeper/report-results",
				"/mgmt/tm/security/firewall", "/mgmt/tm/sys/alert/lcd", "/mgmt/tm/ltm/profile",
				"/mgmt/shared/authz/users-adapter", "/mgmt/tm/cloud/ltm/virtual-servers",
				"/mgmt/tm/ltm/data-group/internal", "/mgmt/shared/iapp/block-refresh-audit", "/mgmt/tm/cm/add-to-trust",
				"/mgmt/tm/analytics/ip-layer/report-results", "/mgmt/net/route-mgmt-entry",
				"/mgmt/tm/live-update/asm-attack-signatures/installations", "/mgmt/tm/sys/turboflex/profile",
				"/mgmt/tm/analytics/ip-intelligence/report-results", "/mgmt/shared/device-group-key-pairs",
				"/mgmt/tm/sys/scriptd", "/mgmt/shared/identified-devices/config/device-finder",
				"/mgmt/tm/net/tunnels/ipip", "/mgmt/shared/resolver/device-group-remover", "/mgmt/tm/sys/raid/array",
				"/mgmt/shared/nodejs/process/memory/log", "/mgmt/tm/analytics/asm-enforced-entities/generate-report",
				"/mgmt/tm/ltm/message-routing/diameter/profile/session",
				"/mgmt/tm/live-update/credential-stuffing/availability", "/mgmt/tm/sys/turboflex/profile-config",
				"/mgmt/shared/iapp/strict-icr-configuration", "/mgmt/tm/net/cos/traffic-priority",
				"/mgmt/tm/sys/sflow/data-source", "/mgmt/shared/task-scheduler/scheduler",
				"/mgmt/tm/analytics/realtime/ram", "/mgmt/tm/sys/dynad", "/mgmt/tm/ltm/monitor",
				"/mgmt/tm/sys/raid/disk", "/mgmt/tm/access/session/kill-sessions", "/mgmt/tm/util/ssldump",
				"/mgmt/tm/ltm/monitor/none", "/mgmt/tm/sys/disk/application-volume", "/mgmt/sys/disk-info",
				"/mgmt/shared/restricted-store/keys", "/mgmt/shared/inflate", "/mgmt/tm/sys/pptp-call-info",
				"/mgmt/tm/util/ping", "/mgmt/net/system-information", "/mgmt/tm/ltm/dns/cache/records/nameserver",
				"/mgmt/tm/sys/crypto/cert-validation-response/ocsp", "/mgmt/tm/analytics/fw-nat/report-results",
				"/mgmt/tm/net/multicast-globals", "/mgmt/shared/file-transfer/madm",
				"/mgmt/tm/analytics/generic/generate-report", "/mgmt/tm/analytics/tcp-analytics/generate-report",
				"/mgmt/tm/sys/ha-mirror", "/mgmt/shared/iapp/file-management", "/mgmt/tm/sys/file/ifile",
				"/mgmt/tm/sys/datastor", "/mgmt/shared/file-transfer/apm-log-templates",
				"/mgmt/tm/analytics/virtual/generate-report", "/mgmt/tm/sys/daemon-log-settings/mcpd",
				"/mgmt/tm/sys/hardware", "/mgmt/tm/sys/performance", "/mgmt/tm/ltm/profile/icap",
				"/mgmt/tm/access/profile-rewrite-stats", "/mgmt/tm/net/tunnels/fec",
				"/mgmt/tm/ltm/dns/cache/validating-resolver", "/mgmt/shared/gossip-conflicts",
				"/mgmt/tm/ltm/auth/radius", "/mgmt/cm/autodeploy/reboot-device",
				"/mgmt/tm/analytics/application-security-network/generate-report", "/mgmt/tm/security/presentation",
				"/mgmt/device/big-ip/change-sources", "/mgmt/tm/sys/file/data-group",
				"/mgmt/tm/analytics/apm-api-protection/report-results", "/mgmt/tm/analytics/dos-l3/report-results",
				"/mgmt/tm/cloud/templates/iapp", "/mgmt/tm/analytics/asm-learning-suggestions/report-results",
				"/mgmt/tm/ltm/profile/rewrite", "/mgmt/tm/live-update/behavioral-waf/update-files",
				"/mgmt/tm/ltm/tacdb", "/mgmt/tm/live-update/threat-campaigns/install-schedule", "/mgmt/tm/ltm/nat",
				"/mgmt/tm/net/tunnels/ipsec", "/mgmt/tm/ltm/monitor/radius-accounting", "/mgmt/tm/sys/ltcfg-instance",
				"/mgmt/tm/sys/crypto/nethsm-test", "/mgmt/tm/analytics/dos-vis-common/report-results", "/mgmt/tm/ltm",
				"/mgmt/tm/analytics/realtime-session/dns", "/mgmt/tm/ltm/message-routing/mqtt/profile/router",
				"/mgmt/tm/asm/file-transfer/uploads", "/mgmt/tm/ltm/auth/tacacs", "/mgmt/sys/host-info-stat",
				"/mgmt/shared/echo-query", "/mgmt/tm/cm/config-sync",
				"/mgmt/tm/ltm/message-routing/mqtt/transport-config", "/mgmt/tm/ltm/profile/mqtt",
				"/mgmt/shared/authz/tmos-role-sync", "/mgmt/tm/analytics/asm-cpu/report-results",
				"/mgmt/tm/util/ccmode", "/mgmt/tm/sys/crypto/cert-validation-response", "/mgmt/tm/net/ipsec/ike-sa",
				"/mgmt/tm/net/rate-shaping/color-policer", "/mgmt/tm/access/file-download/customization-image",
				"/mgmt/tm/sys/disk/logical-disk", "/mgmt/tm/ltm/persistence/persist-records",
				"/mgmt/tm/net/cos/global-settings", "/mgmt/tm/sys/log-config/destination/local-database",
				"/mgmt/tm/sys/sflow/data-source/vlan", "/mgmt/tm/sys/availability",
				"/mgmt/tm/analytics/afm-sweeper/generate-report", "/mgmt/tm/ltm/dns/cache/records",
				"/mgmt/tm/ltm/profile/fastl4", "/mgmt/tm/auth/remote-user", "/mgmt/tm/ltm/message-routing/mqtt/profile",
				"/mgmt/tm/access/usecase-pack-info", "/mgmt/shared/time", "/mgmt/tm/sys/management-ip",
				"/mgmt/tm/cli/alias/shared", "/mgmt/tm/analytics/protocol-inspection/generate-report",
				"/mgmt/tm/sys/ipfix", "/mgmt/shared/device-certificate-update", "/mgmt/tm/ltm/profile/ftp",
				"/mgmt/tm/sys/sflow/data-source/system", "/mgmt/tm/util/get-dossier",
				"/mgmt/tm/analytics/ssl-orchestrator/generate-report", "/mgmt/tm/ltm/profile/server-ldap",
				"/mgmt/tm/sys/sflow/global-settings/interface", "/mgmt/tm/ltm/profile/dns", "/mgmt/tm/sys/failover",
				"/mgmt/tm/ltm/persistence/host", "/mgmt/tm/sys/ip-address", "/mgmt/shared/diagnostics/traces",
				"/mgmt/tm/cli/history", "/mgmt/tm/ltm/profile/netflow", "/mgmt/shared/authz/local-roles",
				"/mgmt/tm/live-update/credential-stuffing/installations", "/mgmt/shared/certificate-whitelist",
				"/mgmt/tm/net/tunnels/etherip", "/mgmt/tm/ltm/profile/quic", "/mgmt/tm/access/query-user-group-tasks",
				"/mgmt/tm/sys/application/template", "/mgmt/tm/ltm/profile/ipother",
				"/mgmt/tm/ltm/dns/cache/records/all", "/mgmt/tm/ltm/monitor/pop3", "/mgmt/cm",
				"/mgmt/cm/system/authn/providers/tmos/1f44a60e-11a7-3c51-a49f-82983026b41b/users",
				"/mgmt/tm/analytics/realtime-session/sip", "/mgmt/tm/ltm/profile/response-adapt",
				"/mgmt/tm/net/routing/route-map", "/mgmt/tm/auth/radius-server", "/mgmt/tm/sys/mac-address",
				"/mgmt/tm/ltm/message-routing/sip/pmbr-stats", "/mgmt/shared/gossip-peer-refresher",
				"/mgmt/shared/irule/downloads", "/mgmt/tm/analytics/lsn-pool/report-results",
				"/mgmt/tm/sys/software/block-device-image", "/mgmt/shared/iapp/directory-management",
				"/mgmt/tm/ltm/monitor/diameter", "/mgmt/tm/ltm/persistence/ssl", "/mgmt/tm/sys/crypto/cert",
				"/mgmt/shared/post-certificate-forever-tasks", "/mgmt/tm/analytics/lsn-pool/generate-report",
				"/mgmt/tm/cli/admin-partitions", "/mgmt/tm/live-update/server-technologies/availability",
				"/mgmt/tm/ltm/profile/httprouter", "/mgmt/tm/cm/sha1-fingerprint", "/mgmt/tm/ltm/monitor/tcp",
				"/mgmt/tm/ltm/profile/stream", "/mgmt/tm/analytics/protocol-security-http/generate-report",
				"/mgmt/shared/analytics/event-analysis-tasks", "/mgmt/shared/stats-information",
				"/mgmt/sys/certificate-file-object", "/mgmt/tm/live-update/bot-signatures/install-schedule",
				"/mgmt/tm/util/clientssl-ciphers", "/mgmt/tm/util/tcpdump", "/mgmt/tm/access/acl-stats",
				"/mgmt/shared/settings/api-status/log/resource", "/mgmt/tm/sys/classification-signature",
				"/mgmt/tm/sys/version", "/mgmt/shared/resolver/device-groups/tm-shared-all-big-ips/devices/event/types",
				"/mgmt/tm/net/rate-shaping/class", "/mgmt/cm/autodeploy/qkview", "/mgmt/tm/ltm/profile/fasthttp",
				"/mgmt/tm/wom", "/mgmt/tm/ltm/profile/ocsp-stapling-params", "/mgmt/tm/ltm/monitor/real-server",
				"/mgmt/tm/sys/disk/directory", "/mgmt/tm/analytics/sip/generate-report",
				"/mgmt/tm/ltm/message-routing/diameter/profile", "/mgmt/tm/ltm/monitor/https",
				"/mgmt/tm/ltm/profile/connector", "/mgmt/cm/autodeploy/software-images", "/mgmt/tm/ltm/monitor/imap",
				"/mgmt/shared/guest-access-check", "/mgmt/tm/analytics/asm-memory/generate-report",
				"/mgmt/tm/auth/password", "/mgmt/tm/sys/file/system-ssl-cert", "/mgmt/shared/diagnostics/device-stats",
				"/mgmt/net/interface", "/mgmt/tm/sys/httpd", "/mgmt/tm/analytics/virtual/report-results",
				"/mgmt/tm/ltm/profile/mblb", "/mgmt/tm/ltm/clientssl-proxy/cached-certs",
				"/mgmt/tm/live-update/bot-signatures/availability", "/mgmt/tm/sys/performance/ramcache",
				"/mgmt/tm/sys/software/volume", "/mgmt/tm/sys/sflow/data-source/interface",
				"/mgmt/tm/util/finalize-custom-ami", "/mgmt/tm/ltm/profile/tcp-analytics", "/mgmt/tm/auth",
				"/mgmt/net/software-image", "/mgmt/tm/ltm/persistence/source-addr", "/mgmt/tm/sys/alert",
				"/mgmt/tm/sys/daemon-log-settings", "/mgmt/tm/sys/icall/event",
				"/mgmt/tm/live-update/threat-campaigns/update-files", "/mgmt/tm/sys/crypto/acceleration-strategy",
				"/mgmt/tm/ltm/profile/ntlm", "/mgmt/tm/ltm/profile/http-compression",
				"/mgmt/tm/ltm/profile/request-log", "/mgmt/tm/net/routing/debug", "/mgmt/tm/ltm/monitor/http2",
				"/mgmt/tm/net/fdb/tunnel", "/mgmt/tm/ltm/profile/qoe", "/mgmt/tm/util/establish-adfs-trust",
				"/mgmt/tm/ltm/monitor/scripted", "/mgmt/tm/task", "/mgmt/tm/analytics/ip-intelligence/generate-report",
				"/mgmt/tm/analytics/dos-vis-common/generate-report", "/mgmt/tm/sys/outbound-smtp", "/mgmt/net/vlan",
				"/mgmt/tm/sys/fpga/firmware-config", "/mgmt/tm/sys/traffic", "/mgmt/shared/iapp/health-prefix-map",
				"/mgmt/tm/auth/partition", "/mgmt/tm/file/apm/aaa/securid-config-files",
				"/mgmt/tm/ltm/dns/dns-express-db", "/mgmt/shared/device-partition", "/mgmt/shared/tmsh-tabc",
				"/mgmt/shared/settings/api-status/log/resource-property", "/mgmt/tm/access/file-download/opswat",
				"/mgmt/shared/iapp/block-configuration-tasks", "/mgmt/tm/net/mroute", "/mgmt/tm/ltm/monitor/postgresql",
				"/mgmt/tm/sys/sflow" };
		for (final String input : inputsArr) {
			System.out.println(String.format("Input: %50s; ICRD_Call: %s", input, isIcrdCall(input)));
		}
	}

	private static final Pattern ICRD_URI_PATTERN = Pattern.compile("^(\\/mgmt)?(\\/)?(tm|cm|sys|access|device|net|odata|subscriptions|toc).*$");
	private static final boolean isIcrdCall(final String requestURI) {
		return ICRD_URI_PATTERN.matcher(requestURI).matches();
	}

}
